### ISSUE TITLE
Uncaught Error: Equality error: general function equality is undecidable, and therefore, unsupported

### ISSUE THREAD

**Issue by vankeisb** [mdgriffith/elm-style-animation#10]
Hi again !

I ran into an issue using `elm-style-animation`. I'm getting this error (sporadically) :

    Uncaught Error: Equality error: general function equality is undecidable, and therefore, unsupported

My model is a `List TreeNode` with 

````
type alias TreeNode = {
    ...
    style : Style.Animation
}
````

I never test for equality (`==` or `/=`) myself on these records, do I'm not sure if I'm misusing the lib, or if it's an actual bug on your side. Plus I'm too much of an Elm noob to say right now. 

Any idea ?

**Comment by mdgriffith** [comment]
Hello!

From what I can find elm throws that error when trying to compare two functions.
https://github.com/elm-lang/elm-compiler/issues/1122

The Style.Animation model does have one place that stores a function in the data in some cases, though I think that should only be there if you're using Style.update.

I believe the easiest solution is to write a custom equality function where you render out each style and compare the rendered version, as well as all the other values.

Something like:

treeNodeEq : TreeNode -> TreeNode -> Bool
treeNodeEq node1 node2 =
             (Style.render node1.style) == (Style.render node2.style)
        && node1.prop1 == node2.prop1
        && node1.prop2 == node2.prop2

**Comment by vankeisb** [comment]
I tried to put together a test case for narrowing the problem, and I don't have it with the "bare minimum". I think it's somewhere else in my code. Sorry for the noise !
