### ISSUE TITLE
Unable to define types in application code

### ISSUE THREAD

**Issue by karls** [mdgriffith/elm-style-animation#15]
Hi,

It looks like `elm-style-animation` does not export the various types the library uses internally, e.g `Animation` and various things from `Animation.Model`. While the examples in `examples/` work fine, some top-level definitions lack type annotations. 

I compile all my Elm code with `--warn` turned on. The compiler warns me about missing type annotations, and even offers inferred ones, but I'm unable to do anything, because I'm unable to import the necessary bits.

Would it be possible to "open up" the types slightly? Perhaps in the next version? Or maybe there is an alternative solution?

Thanks!

**Comment by mdgriffith** [comment]
Hi, thanks for checking out the library!

The only types for type annotations you should need are `Animation.State`, `Animation.Msg`, and `Animation.Messenger.State msg`. 

If you're still prevented from writing a type signature, can you show me the function you're writing?

**Comment by karls** [comment]
Hey, thanks for a prompt reply.

Yup, `Animation.Property` is certainly one of the needed types. And by the same analogy, `Animation.Interpolation` as well.

E.g this example https://github.com/mdgriffith/elm-style-animation/blob/3.0.0/examples/SideMenu.elm#L23-L32 will complain about missing type annotations with `--warn` turned on. I think, currently, it's not possible to satisfy the warnings..?

**Comment by mdgriffith** [comment]
Ok, great.  I found one or two more types that should probably be exposed well.  

I'm going to hold off releasing this as a minor update for a few days just to see if anything else pops up that I can address as well, but I'll update this issue once the release is done!

**Comment by karls** [comment]
Super! Thank you!

**Comment by mdgriffith** [comment]
Just released 3.1.0 which should have all the types needed!

**Comment by karls** [comment]
Thanks!
