### ISSUE TITLE
Unable to define custom color property

### ISSUE THREAD

**Issue by tolgap** [mdgriffith/elm-style-animation#19]
I have an SVG that uses a `linearGradient` `def` as its `fill`. Now I want to animate that `linearGradient`, but the properties are not in the list of exposed functions in `elm-style-animation`. If the function `colorProp` were exposed, I could do this as I wanted without exposing the `Property` type.

Would there be any objection to the idea of exposing `colorProp`?

**Comment by mdgriffith** [comment]
I'm open to the idea.  Though I can just support the properties directly as well :)

Is the color property you're talking about [`stop-color`](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stop-color)?  Are there any others?

**Comment by tolgap** [comment]
I'm specifically talking about `stop-color` yes. Also, `offset` belongs to the `<stop>` as well (to set the stop offset for the gradient). I can't find [`offset`](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/offset) documentation on Mozilla, but it is between 0 and 1.

Of course, exposing `Property` would allow all freedom for developers, so that would also fix it for me. But exposing `Property` could hurt users when breaking changes are introduced the type constructors, so I personally would not choose that solution.

**Comment by mdgriffith** [comment]
Ok, cool.  

There is a current way to animate a custom 1 value property called `Animation.custom` where you could do something like `Animation.custom "offset" 0 "%"`.  (I found an example using %)

I should be ready to release v3.1.0 soon which will have `stopColor`, `offset` and `customColor`.

There will be a few other ways to set custom properties as well.

**Comment by tolgap** [comment]
Great, thank you for the swift responses!

**Comment by mdgriffith** [comment]
Just released 3.1.0 with the above props!
