### ISSUE TITLE
Style attribute in svg not rendered in firefox

### ISSUE THREAD

**Issue by jhrcek** [mdgriffith/elm-style-animation#20]
See example program [in gist](https://gist.github.com/jhrcek/a7a9046fe2d082da385ea7dfb7c557cc)

When I open the program (in elm reactor or compile it using `elm make Main.js`) in google-chrome, it works fine (mouse over the circle to see it move).

But when I run it in firefox (v 47, running on Fedora 22), the style attribute of circle is not rendered at all (so the circle doesn't move). Is this a bug or am I doing something wrong?

**Comment by mdgriffith** [comment]
Interesting.  Here's what I think is going on.  There are only some svg properties that can be set via css/style property, the rest have to be custom attributes on the svg itself.

I think Chrome probably respects `cx` and `cy` in css, but firefox doesn't.  

When I get some time I'll look into it.  It's a relatively easy change to make, but I don't think I'll have time until next week.

**Comment by mdgriffith** [comment]
Just released 3.2.0 which should address this!

**Comment by jhrcek** [comment]
Works perfectly now. Thanks for the fix!
