### ISSUE TITLE
text-shadow values don't match css syntax

### ISSUE THREAD

**Issue by mcade** [mdgriffith/elm-style-animation#21]
css syntax for text-shadow: h-shadow v-shadow blur-radius color|none|initial|inherit;

```
textShadow : Shadow -> Animation.Model.Property
textShadow shade =
    let
        { red, green, blue, alpha } =
            Color.toRgb shade.color
    in
        ShadowProperty
            "text-shadow"
            False
            { offsetX = initMotion shade.offsetX "px"
            , offsetY = initMotion shade.offsetY "px"
            , size = initMotion shade.size "px"
            , blur = initMotion shade.blur "px"
            , red = initMotion (toFloat red) "px"
            , green = initMotion (toFloat green) "px"
            , blue = initMotion (toFloat blue) "px"
            , alpha = initMotion alpha "px"
            }
```

**Comment by mdgriffith** [comment]
The argument for shadows is 
```
    { offsetX : Float
    , offsetY : Float
    , size : Float
    , blur : Float
    , color : Color
    }
```

Certain shadows ignore the `size` attribute.  Those that do capture it in the comments: "Text shadows will ignore the shadow's `size` value.   This is just one of the bizarre quirks of CSS."

Which part are you saying doesn't match?

**Comment by mcade** [comment]
I thought a size argument wouldn't exist for textShadow since the css spec doesn't mention anything about the text-shadow attribute having a size value.

**Comment by mdgriffith** [comment]
Ah, got it.  Yeah, some browsers accept it, some don't (though it's usually called `spread`).  Some other shadows have it, some don't.  

I settled for having one shadow type and just noting it in the comments, though maybe in the future I'll have separate shadow types for those that have size/spread and those that don't. :)
