### ISSUE TITLE
translate3d not working properly

### ISSUE THREAD

**Issue by bigardone** [mdgriffith/elm-style-animation#24]
Hi!
I've started using your awesome library to add some animations in a project I'm working on, but I'm having some issues trying to replicate this css animation:

``` sass
@keyframes fadeInDown
  from
    opacity: 0
    transform: translate3d(0, -100%, 0)

  to
    opacity: 1
    transform: none


.fadeInDown
  animation-name: fadeInDown
  animation-duration: 300ms
  animation-fill-mode: both
```

This is my animation initial model:

``` elm
initialModel =
  { ...
   , animationModel =
        { pageFormStyle =
            Animation.style
                [ Animation.translate3d (Animation.percent 0) (Animation.percent -100) (Animation.percent 0)
                , Animation.opacity 0
                ]
        }
    }
```

And here is the update function:

``` elm

ShowCreatePageForm show ->
            let
                pageFormStyle =
                    case show of
                        Hide ->
                            Animation.interrupt
                                [ Animation.to
                                    [ Animation.translate3d (Animation.percent 0) (Animation.percent -100) (Animation.percent 0)
                                    , Animation.opacity 0
                                    ]
                                ]
                                model.animationModel.pageFormStyle

                        Show ->
                            Animation.interrupt
                                [ Animation.to
                                    [ Animation.exactly "transform" "none"
                                    , Animation.opacity 1
                                    ]
                                ]
                                model.animationModel.pageFormStyle
...
```

The problem is that the initial `translate3d` is not being applied, so a white space is shown as it's only applying the `opacity: 0` style:

![image](https://cloud.githubusercontent.com/assets/1090272/19376896/02da07e2-91e2-11e6-974c-fd8900eaf577.png)

When the **\+ Add new** link is clicked to display the form it applies correctly the opacity only, showing it:

![image](https://cloud.githubusercontent.com/assets/1090272/19376961/ac71d9d8-91e2-11e6-8282-c628593ae3ac.png)

Clicking in the **Cancel** button will try to fade and slide up the form, but it only changes the `opacity` leaving the white space again. 
Am I doing anything wrong? Thanks in advance :)

**Comment by mdgriffith** [comment]
First off, thanks for such a well written issue!

After looking around, I've found that apparently the z coordinate for a translate3d cannot be a percentage.  I think you can just switch your z coordinate to pixels and everything should work.

**Comment by bigardone** [comment]
You're welcome :D
I've tried setting the z coordinate  to pixels, but the issue persists.
I'm going to try setting up a quick demo project wiht the both the animation using css frames and your library, so you can see it in action.
Cheers!

**Comment by mdgriffith** [comment]
So, another thing.

`Animation.to [Animation.exactly "transform" "none"]` is probably causing you issues.  `exactly` isn't meant to be used in the `to` function...when it is, it will set that property as soon as the animation is triggered.  So, I would change that to 
`Animation.to [Animation.translate3d (Animation.percent 0) (Animation.percent 0) (Animation.px 0)]` 


`exactly` is supposed to be used only with `Animation.set` and only for properties that aren't supported by the library.

**Comment by mdgriffith** [comment]
Wanted to check up on this, were you able to resolve your issue?
