### ISSUE TITLE
Can't change display attribute after initializing it.

### ISSUE THREAD

**Issue by mcade** [mdgriffith/elm-style-animation#25]
I can initialize a specific displayMode like in this [example](https://github.com/mdgriffith/ui-animation/blob/c96d9c9cb68bd2962a19e8e116903d53e86bf678/examples/Showcase.elm#L234)
but when I try to change the displayMode in my update function it remains whatever its initial value was.

My use case is changing a div's display from none to block.

**Comment by mdgriffith** [comment]
Can you show your code?  Also double check that you're using `Animation.set` to set the displayMode at a certain point instead of `Animation.to`

**Comment by mcade** [comment]
Thanks for pointing me to `set`. 

Instead of trying to change the displayMode in my `Animation.to` function I used `set` after afterwards to remove the div.
