### ISSUE TITLE
Multiple animations affecting the same property fail

### ISSUE THREAD

**Issue by stormont** [mdgriffith/elm-style-animation#32]
I posted this in the Elm Slack #animations channel, but I think it warrants an issue for improvement.

In particular, it would be helpful to log a warning if a list of animations updating a property happen to update the same property from two different animations, like is already done on creation of a _single_ animation modifying the same property multiple times.

It also feels a bit like a bug that a completed animation (`running=False`) could take priority for a property value that is being changed by a still-in-progress animation. I'm not sure what to suggest there (whether a code change, or just highlighting it in the docs, if a code change is too difficult or unreasonable for the package expectations). I could see that going either way.

Here are my comments from the Slack channel, for context (with the link updated to the particular commit at the time). First, the problem I ran into, then the solution.

> I’m struggling a bit with performing a couple of chained commands in a simple animation demo. It looks simple enough and I think I’m chaining them correctly, but it seems like my model state isn’t being maintained correctly.
> 
> Could someone take a look and point out where I’m losing the model state? I can’t seem to find it.
> 
> Link: https://github.com/stormont/elm-animation-examples/commit/0af75f8b9b24562798716d63c15441e7e5141b12
> 
> I’m trying to get a click on one box to get it to fade out, while fading in the other box at the same time, so that there’s always only one box to click. Ignoring the separate problem that both are visible at app start (an intentional debugging change I currently have in place), I can’t seem to get commands to update the model state for both boxes simultaneously, despite seeing both animations running in the Explore History debugger.
> 
> The problem (symptom?) is in the SwapView command. It’s trying to execute an animation on one view, then execute a different animation on a different view, and it naively appears to be chaining the models correctly, as far as I can tell. But, when you run the code, you’ll see that clicking on either box (view) only animates that box, not the other one as well.
> 
> I feel like I’m missing something very small, but I can’t put my finger on it. The problem _seems_ to be unrelated to the actual act of animation and more related to the problem of chaining commands/models.
>
> Supposed to animate both at once.
> 
> If you make the animation identifier “fade_out_fade_in” on both, you’ll see them both animate.
> 
> But when they start from different states, I seem to get different variations of behaviors.
> 
> Also, everything seems to work individually up to this point, but chaining the two commands together makes them go wonky.
> 
> Actually, I take that back. If I _start_ both elements from an opacity of 0 and try to just `(ExecuteAnimation "ElementX" "fade_in")` when clicking on either one, I can’t get them to fade in, either. Definitely seems like some oddness around opacity there.
> 
> Maybe having an animation end at 0 opacity causes some other display side effect? I wouldn’t think so, because you can still click the element and see messages being logged.

And the solution I eventually found:

> For anyone that cares, I was able to root out the problem. It was a combination of my code plus a nuance of the animations package.
> 
> The animations package will only use the last defined instance of any property. If you directly try to use the same property twice in an animation definition, it will console log a warning, but my case was obscuring this. My code here is intentionally trying to make the animations more composable, but that avoids the check for the double-definitions.
> 
> Basically, it's possible to have _two_ different animations running (or even set to "not running"/completed) that affect the same property. In that case, only one will actually run (even if the chosen animation has already completed).
> 
> As opposed to one animation affecting the same property in two ways, which is what the console log checks for.

I avoided the issue in my code by making sure I only ever had one particular animation defined at a time on a given view element, which makes intuitive sense. But, it took me a few days to track the problem down. Others might have the same problem.

**Comment by mdgriffith** [comment]
Thanks for the issue! 

As mentioned in slack, your code is creating a new animation state for every animation.  There should only be one animation state per thing you're animating.  This is generally solved if you use standard elm constructs (like a record) to store your state.  

I don't believe there is an bug in the library so I'm going to go ahead and close this issue, but I appreciate our chat on slack!
