### ISSUE TITLE
Animation.Messenger missing sends

### ISSUE THREAD

**Issue by trotha01** [mdgriffith/elm-style-animation#36]
I only see one Animation.Messenger.send only triggered once, instead of once per animation.

Steps
- I have a list of 3 items, each with an Animation.Messenger.State
- I call Animation.interrupt to start the animation on each item, with an Animation.Messenger.send to notify me when an animation is done.
- I use Animation.Messenger.update for updates on each item.
- I only see Animation.Messenger.send only triggered once, instead of once per item.

The use case is that I want to remove the item from a list when the animation is done.

I'm not sure if I'm using the library incorrectly, here is a gist of the problem:
https://gist.github.com/trotha01/0daa217c07bf05d859c8dcfe88229009

If you run the gist, we see that "start" is logged to the console 3 times, but "done" is only logged once.

Any help is appreciated, thank you!

**Comment by mdgriffith** [comment]
Hello!

So, this one was sneaky: on line `112` switch `==` to `/=`.

**Comment by trotha01** [comment]
Thank you for the quick response! Sorry for the bad code! Love the library 💖
