### ISSUE TITLE
Update elm-community/list-extra

### ISSUE THREAD

**Issue by bparadie** [mdgriffith/elm-style-animation#37]
Right now I can't install `mdgriffith/style-elements` with `mdgriffith/elm-style-animation`, i.e.

```
cd /tmp
mkdir test
cd test
elm-package install mdgriffith/style-elements
elm-package install mdgriffith/elm-style-animation
```

![screen shot 2017-02-13 at 2 35 26 pm](https://cloud.githubusercontent.com/assets/1578115/22906665/6d7d9dfc-f1fa-11e6-9909-e5167110f90a.png)

I believe this is because of `"elm-community/list-extra`. The current version is:
```
To install elm-community/list-extra I would like to add the following
dependency to elm-package.json:

    "elm-community/list-extra": "6.0.0 <= v < 7.0.0"

May I add that to elm-package.json for you? [Y/n] 
```

https://github.com/mdgriffith/elm-style-animation/blob/master/elm-package.json#L15:
```
"elm-community/list-extra": "5.0.0 <= v < 6.0.0",
```

@see https://github.com/mdgriffith/style-elements/issues/7

**Comment by mdgriffith** [comment]
Thanks for the issue.  This has actually been a bit of a problem, trying to keep the version of list-extra that this library uses with whatever the user is trying to use, so I removed it as a dependency in v3.5.4 :)

I'll see if I can do the same for style-elements

**Comment by PublicParadise** [comment]
Thx for the quick fix!
