### ISSUE TITLE
Animating z-index

### ISSUE THREAD

**Issue by popara** [mdgriffith/elm-style-animation#44]
Hi, 

I couldn't find a way to change value of z-index as part of api. 
I have tried `Animation.exact "z-index" "2" ` but it didn't apply on interrupt animations. 

Did you had a reason to opt it out? 

I can make a PR if you are ok with it. 

Cheers

**Comment by mdgriffith** [comment]
Hello!

When you say it didn't apply, do you mean the property didn't show up?

Try using `Animation.set [Animation.exact "z-index" "2"]` as a step.

**Comment by popara** [comment]
Animation.set did the trick.

For some reason I have read that part of docs, but didn't tried with .set

Many thanks Señor :)

**Comment by mdgriffith** [comment]
No problem!

There should probably be a logged warning or something instead of failing silently :).  I'll add that to my v4 checklist.
