### ISSUE TITLE
Animation.display Animation.none -> Animation.display Animation.block is not doing anything

### ISSUE THREAD

**Issue by NeverwinterMoon** [mdgriffith/elm-style-animation#48]
I tried to have animation started with Animation.display Animation.none and transition it to Animation.display Animation.block (along with some translation). Translation works, but the display property never changes. Am I too slow with understanding something or is this as expected?

**Comment by mdgriffith** [comment]
Try putting the `Animation.display` property inside an `Animation.set` after the `Animation.to`.

**Comment by NeverwinterMoon** [comment]
@mdgriffith Thanks for your help! It worked out just as I wanted it. I should have figured this out on my own :(

**Comment by mdgriffith** [comment]
No worries.  If you're not on the elm slack, I recommend getting on there.  I regularly answer questions :)
