### ISSUE TITLE
Expose `isRunning`?

### ISSUE THREAD

**Issue by jesse-c** [mdgriffith/elm-style-animation#61]
Would you be open to exposing the `isRunning` function? My use case is, that when an animation has finished (i.e. opacity 1 → opacity 0), then I'd like to hide the element. To do that I need to know when the animation has finished.

I tried animating the `DisplayMode` property from `none` → `block`, but it didn't work, as the `display` property was never changed.

```
        Animation.styleWith
            (Animation.easing
                { duration = 400 * Time.millisecond
                , ease = identity
                }
            )
            [ Animation.opacity 0.0, Animation.display Animation.none ]
```
```
                            Animation.interrupt
                                [ Animation.to
                                    [ Animation.opacity 0
                                    , Animation.display Animation.none
                                    ]
                                ]
```
```
                    Animation.interrupt
                        [ Animation.to
                            [ Animation.opacity 1
                            , Animation.display Animation.block
                            ]
                        ]
```

**Comment by mdgriffith** [comment]
Yeah, it's a bit unintuitive, but you'll need to use `Animation.set` in order to set `display`.

```elm
Animation.interrupt
    [ Animation.to
        [ Animation.opacity 1
        ]
    , Animation.set
        [ Animation.display Animation.block
        ]
    ]
```

[Small history on why isRunning is not exposed](https://github.com/mdgriffith/elm-style-animation/issues/49)

**Comment by jesse-c** [comment]
Ah, okay! Thank you @mdgriffith. It's working a bit better now—showing the item isn't particularly smooth, but hiding it is.
