### ISSUE TITLE
Animation.set does not work

### ISSUE THREAD

**Issue by dlindenkreuz** [mdgriffith/elm-style-animation#7]
Tried it for Translate3d and got a whole lot of NaN values. I suspect that in Core.elm, some conflicts arise through division by zero because easing time is effectively set to zero for `Animation.set`.

Ex. [Core.elm, Line 666](https://github.com/mdgriffith/elm-html-animation/blob/8913f7ea8e8cf7aa736002fe5b5da5a41b70b9f9/src/Html/Animation/Core.elm#L666) and [Core.elm, Line 565](https://github.com/mdgriffith/elm-html-animation/blob/8913f7ea8e8cf7aa736002fe5b5da5a41b70b9f9/src/Html/Animation/Core.elm#L565)

```elm
mouseDelta' =
  [ Translate3d dx dy 0 Px ]

( annotations', fx ) =
  UI.animate |> UI.set mouseDelta' |> onAnnotation id model.annotations
```

**Comment by mdgriffith** [comment]
Thanks!  This was resolved in the 4.0.0 release
