### ISSUE TITLE
Moving an SVG

### ISSUE THREAD

**Issue by RobertWalter83** [mdgriffith/elm-style-animation#8]
Hi,
great project, but I need help moving an SVG.

I created a "minimal example" (see below) that shows my attempt to move a svg triangle onClick using the Property "D".

Whilst the color change works (to show something is happening), the svg does not move. I'd expect it to move relatively by (-50, -50) units.

What am i doing wrong?
Thanks!

```Elm
import Time exposing (second)
import Html.App
import Html exposing (div, Html)
import Html.Attributes as Attr
import Html.Events exposing (..)
import Svg exposing (..)
import Svg.Attributes exposing (..)
import AnimationFrame
import Style
import Style.Properties exposing (..)
import Color exposing (rgb)


type alias Model =
    { style : Style.Animation  }


type Action
    = Move
    | Animate Float


palette =
    { orange = rgb 244 156 59,
      red = rgb 127 0 0 }


logo =
    [ Points
            <| alignStartingPoint
                [ ( 150, 139.2)
                , ( 150, 239.05 )
                , ( 85.2, 197.15 )
                ]
      , Fill palette.orange
      , D [ ]
    ]
      
    
update : Action -> Model -> ( Model, Cmd Action )
update action model =
    case action of
              
        Move ->
            ( { model 
                | style = 
                    Style.animate
                        |> Style.to [ D [Style.Properties.Move -50 -50], Style.Properties.Fill palette.red ]
                        |> Style.on model.style
              }
            , Cmd.none
            )

        Animate time ->
            ( { model
                | style = Style.tick time model.style
              }
            , Cmd.none
            )


view : Model -> Html Action
view model =
    div
        [ onClick Move
        , Attr.style [ ( "margin", "0px auto" ), ( "width", "300px" ), ( "height", "300px" ), ("cursor", "pointer") ]
        ]
        [ svg
            [ version "1.1"
            , x "0"
            , y "0"
            , viewBox "0 0 300 300" 
            ]
            [ polygon (Style.renderAttr model.style) [] ]
        ]


subscriptions : Model -> Sub Action
subscriptions model =
    AnimationFrame.times Animate


init : ( Model, Cmd Action )
init =
    ( { style = Style.init logo }
    , Cmd.none
    )


main =
    Html.App.program
        { init = init
        , view = view
        , update = update
        , subscriptions = subscriptions
        }
```

**Comment by mdgriffith** [comment]
Hi!

There are a few things:
The 'D' property is only used by the 'path' element.  In this case the polygon is just ignoring that attribute.  (Side note if you were to use the `D` Property on a `path` attribute,you'd need to specify an initial `D` value that has all the commands in it, though set to their initial values...so `Move 0 0` would need to be  there).

To actually get it a polygon to move, you need to use  the `Translate` transform.

So you'd need to make these changes


Your animation
`
 Style.animate
           |> Style.to [ Style.Properties.Translate -50 -50 Px
                            , Style.Properties.Fill palette.red ]
           |> Style.on model.style

`
initial value
`
   [ Points
            <| alignStartingPoint
                [ ( 150, 139.2)
                , ( 150, 239.05 )
                , ( 85.2, 197.15 )
                ]
      , Fill palette.orange
      , Style.Properties.Translate 0 0 Px
    ]

`
and on rendering you need to render both the attributes and the style properties...which is done like so:
`
polygon ([Attr.style <| Style.render model.style] ++ Style.renderAttr model.style) []
`

**Comment by RobertWalter83** [comment]
Great, thanks, it works now.
